version: "3"
services:
  node-app:
    image: 118381122830.dkr.ecr.ap-southeast-2.amazonaws.com/node-app:2.0
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27015:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
      - 8083:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
